---
- hosts: all
  vars:
    travis_user: "travis"
    travis_password: "iPxoMYWOri3eg"
    travis_home: "/home/{{ travis_user }}"
    lmd_dir: "{{ travis_home }}/linux-minidisc"
  pre_tasks:
    - name: Apt-get Update
      become: true
      apt: update_cache=yes

    - name: Install Build Essentials
      become: true
      apt: name=build-essential

    - name: Install Git
      become: true
      apt: name=git

    - name: Install gettext
      become: true
      apt: name=gettext

    - name: Install cmake
      become: true
      apt: name=cmake


  tasks:
   - name: Create Travis User
     become: true
     user: name={{ travis_user }}
           password={{ travis_password }}
           comment="Travis User"
           createhome=yes
           home={{ travis_home }}

   - name: Enable passwordless sudo for travis user
     become: true
     copy: content="%{{ travis_user }} ALL=(ALL) NOPASSWD:ALL"
           dest=/etc/sudoers.d/{{ travis_user }}
           owner=root
           group=root
           mode=0440

   - name: Clone linux-minidisc repo
     become: true
     become_user: "{{ travis_user }}"
     git:  repo=https://github.com/deenine/linux-minidisc
           version=himd-json
           dest={{ lmd_dir }}


   - name: Install dependencies (mingw32)
     become: true
     become_user: "{{ travis_user }}"
     args:
       chdir: "{{ lmd_dir }}"
     environment:
       BUILD_TYPE: "linux-cross-mingw32"
     command: "sh build/install_dependencies.sh"


  - name: qmake (mingw32)
    become: true
    become_user: "{{ travis_user }}"
    args:
      chdir: "{{ lmd_dir }}"
    environment:
      BUILD_TYPE: "linux-cross-mingw32"
    command: "sh build/cross_wrapper_mingw.sh qmake CONFIG+=without_gui"

  - name: make (mingw32)
    become: true
    become_user: "{{ travis_user }}"
    args:
      chdir: "{{ lmd_dir }}"
    environment:
      BUILD_TYPE: "linux-cross-mingw32"
    command: "sh build/cross_wrapper_mingw.sh make"

  - name: Package Build
    become: true
    become_user: "{{ travis_user }}"
    args:
      chdir: "{{ lmd_dir }}"
    environment:
      BUILD_TYPE: "linux-cross-mingw32"
    command: "sh build/package_build.sh"

  - name: Copy Build to Host
    become: true
    become_user: "root"
    copy:
      src: "{{ lmd_dir }}/dist"
      dest: "/build"
      remote_src: yes
